/*
LICENCIA JOSE JAVIER BO
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
Lista de paquetes:
 */
package ud1_ejer10.gui.ventanas;

import javax.swing.JOptionPane;
import ud1_ejer10.logica.Logica;

/**
 *
 * @author Jose Javier Bailon Ortiz
 */
public class VPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio10VentanaPrincipal
     */
    public VPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInputUsuario = new javax.swing.JPanel();
        lbiNombre = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        lbiApellidos = new javax.swing.JLabel();
        inputApellidos = new javax.swing.JTextField();
        panelMenuPrincipal = new javax.swing.JPanel();
        btnIniciaMezcladora = new javax.swing.JButton();
        btnIniciaAppMinisterio = new javax.swing.JButton();
        btnRegistroDerportivo = new javax.swing.JButton();
        btnImitador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbiNombre.setText("Nombre:");
        panelInputUsuario.add(lbiNombre);

        inputNombre.setPreferredSize(new java.awt.Dimension(100, 22));
        panelInputUsuario.add(inputNombre);

        lbiApellidos.setText("Apellidos:");
        panelInputUsuario.add(lbiApellidos);

        inputApellidos.setPreferredSize(new java.awt.Dimension(100, 22));
        panelInputUsuario.add(inputApellidos);

        panelMenuPrincipal.setLayout(new java.awt.GridLayout(4, 1, 0, 10));

        btnIniciaMezcladora.setText("Mezcladora de nombres");
        btnIniciaMezcladora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciaMezcladoraActionPerformed(evt);
            }
        });
        panelMenuPrincipal.add(btnIniciaMezcladora);

        btnIniciaAppMinisterio.setText("App Ministerio");
        btnIniciaAppMinisterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciaAppMinisterioActionPerformed(evt);
            }
        });
        panelMenuPrincipal.add(btnIniciaAppMinisterio);

        btnRegistroDerportivo.setText("Registro Deportivo");
        panelMenuPrincipal.add(btnRegistroDerportivo);

        btnImitador.setText("Imitador");
        btnImitador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImitadorActionPerformed(evt);
            }
        });
        panelMenuPrincipal.add(btnImitador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInputUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(panelMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInputUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciaMezcladoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciaMezcladoraActionPerformed
        if (!Logica.mezclarInicio(getUsuario()))
            mostrarErrorUsuario();
    }//GEN-LAST:event_btnIniciaMezcladoraActionPerformed

    private void btnImitadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImitadorActionPerformed
        if (!Logica.imitadorInicio(getUsuario()))
            mostrarErrorUsuario();
    }//GEN-LAST:event_btnImitadorActionPerformed

    private void btnIniciaAppMinisterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciaAppMinisterioActionPerformed
        if (!Logica.appMinisterioInicio(getUsuario()))
            mostrarErrorUsuario();
    }//GEN-LAST:event_btnIniciaAppMinisterioActionPerformed

    /**
     * Devuelve el nombre compuesto del usuario
     *
     * @return El nombre compuesto
     */
    private String getUsuario() {
        return inputNombre.getText() + " " + inputApellidos.getText();
    }

    private void mostrarErrorUsuario() {
        JOptionPane.showMessageDialog(this, "No puede dejar el nombre de usuario vacio", "Error", JOptionPane.ERROR_MESSAGE);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImitador;
    private javax.swing.JButton btnIniciaAppMinisterio;
    private javax.swing.JButton btnIniciaMezcladora;
    private javax.swing.JButton btnRegistroDerportivo;
    private javax.swing.JTextField inputApellidos;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JLabel lbiApellidos;
    private javax.swing.JLabel lbiNombre;
    private javax.swing.JPanel panelInputUsuario;
    private javax.swing.JPanel panelMenuPrincipal;
    // End of variables declaration//GEN-END:variables

}//fin Ejercicio10VentanaPrincipal
