/*
LICENCIA JOSE JAVIER BO
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
Lista de paquetes:
 */
package ud1_ejer10.gui.ventanas;

import javax.swing.JOptionPane;
import ud1_ejer10.logica.Logica;

/**
 *
 * @author Jose Javier Bailon Ortiz
 */
public class VPrincipal extends javax.swing.JFrame {

    /**
     * Ventana principal de la aplicacion. Tiene dos campos para recoger nombre
     * y apellidos y varios botones para abrir una ventana aparte con diferentes
     * aplicaciones. Le suministra el nombre y apellido recogidos a la logica
     * para que al lanzar las otras aplicaciones les pase ese nombre y apellidos
     */
    public VPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInputUsuario = new javax.swing.JPanel();
        lbiNombre = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        lbiApellidos = new javax.swing.JLabel();
        inputApellidos = new javax.swing.JTextField();
        panelMenuPrincipal = new javax.swing.JPanel();
        btnIniciaMezcladora = new javax.swing.JButton();
        btnIniciaAppMinisterio = new javax.swing.JButton();
        btnRegistroDerportivo = new javax.swing.JButton();
        btnImitador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbiNombre.setText("Nombre:");
        panelInputUsuario.add(lbiNombre);

        inputNombre.setPreferredSize(new java.awt.Dimension(100, 22));
        panelInputUsuario.add(inputNombre);

        lbiApellidos.setText("Apellidos:");
        panelInputUsuario.add(lbiApellidos);

        inputApellidos.setPreferredSize(new java.awt.Dimension(100, 22));
        panelInputUsuario.add(inputApellidos);

        panelMenuPrincipal.setLayout(new java.awt.GridLayout(4, 1, 0, 10));

        btnIniciaMezcladora.setText("Mezcladora de nombres");
        btnIniciaMezcladora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciaMezcladoraActionPerformed(evt);
            }
        });
        panelMenuPrincipal.add(btnIniciaMezcladora);

        btnIniciaAppMinisterio.setText("App Ministerio");
        btnIniciaAppMinisterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciaAppMinisterioActionPerformed(evt);
            }
        });
        panelMenuPrincipal.add(btnIniciaAppMinisterio);

        btnRegistroDerportivo.setText("Registro Deportivo");
        btnRegistroDerportivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroDerportivoActionPerformed(evt);
            }
        });
        panelMenuPrincipal.add(btnRegistroDerportivo);

        btnImitador.setText("Imitador");
        btnImitador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImitadorActionPerformed(evt);
            }
        });
        panelMenuPrincipal.add(btnImitador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInputUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(panelMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInputUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * click del boton iniciar mezclador. Comprueba que se hayan cumplimentado
     * los campos d enombre y apellido y si se han rellenado lanza la ventana de
     * la aplicacion
     *
     * @param evt
     */
    private void btnIniciaMezcladoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciaMezcladoraActionPerformed
        if (!Logica.nombreUsuarioValidoParaTitulo(inputNombre.getText(), inputApellidos.getText()))
            mostrarErrorUsuario();
        else {
            String usuarioPrincipal = inputNombre.getText() + " " + inputApellidos.getText();
            VMezclar ventanaMezclar = new VMezclar(usuarioPrincipal);
            ventanaMezclar.setLocationRelativeTo(null);
            ventanaMezclar.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnIniciaMezcladoraActionPerformed

    /**
     * click del boton iniciar imitador. Comprueba que se hayan cumplimentado
     * los campos d enombre y apellido y si se han rellenado lanza la ventana de
     * la aplicacion
     *
     * @param evt
     */
    private void btnImitadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImitadorActionPerformed
        if (!Logica.nombreUsuarioValidoParaTitulo(inputNombre.getText(), inputApellidos.getText()))
            mostrarErrorUsuario();
        else {
            String usuarioPrincipal = inputNombre.getText() + " " + inputApellidos.getText();
            VImitador ventanaImitador = new VImitador(usuarioPrincipal);
            ventanaImitador.setLocationRelativeTo(null);
            ventanaImitador.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnImitadorActionPerformed

    /**
     * click del boton iniciar app ministerio. Comprueba que se hayan
     * cumplimentado los campos d enombre y apellido y si se han rellenado lanza
     * la ventana de la aplicacion
     *
     * @param evt
     */
    private void btnIniciaAppMinisterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciaAppMinisterioActionPerformed
        if (!Logica.nombreUsuarioValidoParaTitulo(inputNombre.getText(), inputApellidos.getText()))
            mostrarErrorUsuario();
        else {
            String usuarioPrincipal = inputNombre.getText() + " " + inputApellidos.getText();
            VMinisterio ventanaMinisterio = new VMinisterio(usuarioPrincipal);
            ventanaMinisterio.setLocationRelativeTo(null);
            ventanaMinisterio.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnIniciaAppMinisterioActionPerformed

    /**
     * click del boton iniciar registro deportivo. Comprueba que se hayan cumplimentado
     * los campos d enombre y apellido y si se han rellenado lanza la ventana de
     * la aplicacion
     *
     * @param evt
     */
    private void btnRegistroDerportivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroDerportivoActionPerformed
        if (!Logica.nombreUsuarioValidoParaTitulo(inputNombre.getText(), inputApellidos.getText()))
            mostrarErrorUsuario();
        else {
            String nombreUsuarioTitulo = inputNombre.getText() + " " + inputApellidos.getText();
            VRegistroAcceso ventanaRegistroAcceso = new VRegistroAcceso(nombreUsuarioTitulo);
            ventanaRegistroAcceso.setLocationRelativeTo(null);
            ventanaRegistroAcceso.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnRegistroDerportivoActionPerformed

    /**
     * Muestra un error avisando de que se deben rellenar los campos de nombre y apellidos
     */
    private void mostrarErrorUsuario() {
        JOptionPane.showMessageDialog(this, "No puede dejar el nombre y/o apellidos vacio", "Error", JOptionPane.ERROR_MESSAGE);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImitador;
    private javax.swing.JButton btnIniciaAppMinisterio;
    private javax.swing.JButton btnIniciaMezcladora;
    private javax.swing.JButton btnRegistroDerportivo;
    private javax.swing.JTextField inputApellidos;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JLabel lbiApellidos;
    private javax.swing.JLabel lbiNombre;
    private javax.swing.JPanel panelInputUsuario;
    private javax.swing.JPanel panelMenuPrincipal;
    // End of variables declaration//GEN-END:variables

}//fin Ejercicio10VentanaPrincipal
